from operator import le


class TargetWellInformation:
    def __init__(self, 
                id: int=None,
                name: str=None,
                api: str=None,
                afe_landing_zone: str=None,
                logs_landing_zone: str=None,
                enverus_status: str=None,
                afe_md_ft: int=None,
                afe_bhl_tvd_ft: int=None,
                surveys_preforated_interval_ft: int=None,
                afe_gross_dollar: float=None,
                well_cost: float=None,
                seller_effective_gross_nri_percentage: float=None,
                seller_net_nri_percentage: float=None,
                seller_gross_for_sale_percentage: float=None,
                afe_gwi_for_sale_net_capital_dollar: float=None,
                enverus_rkb_elevation_ft: int=None,
                bhl_tvd_ss_ft: int=None,
                afe_in_landing_zone_hyp_spacing_ft: int=None,
                state: str=None,
                county: str=None,
                tx_abstract_southwest_corner: str=None,
                tx_block_southwest_corner: str=None,
                nw_township_southwest_corner: str=None,
                nm_range_southwest_corner: str=None,
                nm_tx_section_southwest_corner: str=None,
                nad_system: str=None,
                nad_zone: str=None,
                x_surface_location: float=None,
                y_surface_location: float=None,
                x_first_take_point: float=None,
                y_first_take_point: float=None,
                x_last_take_point: float=None,
                y_last_take_point: float=None,
                x_bottom_hole: float=None,
                y_bottom_hole: float=None,
                latitude_surface_location: str=None,
                longitude_surface_location: str=None,
                latitude_first_take_point: str=None,
                longitude_first_take_point: str=None,
                latitude_last_take_point: str=None,
                longitude_last_take_point: str=None,
                latitude_bottom_hole: str=None,
                longitude_bottom_hole: str=None,
                legal_tx_abstract_surface_location: str=None,
                Legal_tx_block_surface_location: str=None,
                legal_nw_township_surface_location: str=None,
                legal_nm_tx_section_surface_location: str=None,
                legal_fnl_surface_location: str=None,
                legal_fsl_surface_location: str=None,
                legal_fwl_surface_location: str=None,
                legal_fel_surface_location: str=None,
                legal_tx_abstract_first_take_point: str=None,
                Legal_tx_block_first_take_point: str=None,
                legal_nw_township_first_take_point: str=None,
                legal_nm_tx_section_first_take_point: str=None,
                legal_fnl_first_take_point: str=None,
                legal_fsl_first_take_point: str=None,
                legal_fwl_first_take_point: str=None,
                legal_fel_first_take_point: str=None,
                legal_tx_abstract_last_take_point: str=None,
                Legal_tx_block_last_take_point: str=None,
                legal_nw_township_last_take_point: str=None,
                legal_nm_tx_section_last_take_point: str=None,
                legal_fnl_last_take_point: str=None,
                legal_fsl_last_take_point: str=None,
                legal_fwl_last_take_point: str=None,
                legal_fel_last_take_point: str=None,
                legal_tx_abstract_bottom_hole: str=None,
                Legal_tx_block_bottom_hole: str=None,
                legal_nw_township_bottom_hole: str=None,
                legal_nm_tx_section_bottom_hole: str=None,
                legal_fnl_bottom_hole: str=None,
                legal_fsl_bottom_hole: str=None,
                legal_fwl_bottom_hole: str=None,
                legal_fel_bottom_hole: str=None,
                perf_interval_ft: int=None):
        
        self.id =id
        self.name = name
        self.api = api
        self.afe_landing_zone = afe_landing_zone
        self.logs_landing_zone = logs_landing_zone
        self.enverus_status = enverus_status
        self.afe_md_ft = afe_md_ft
        self.afe_bhl_tvd_ft = afe_bhl_tvd_ft
        self.surveys_preforated_interval_ft = surveys_preforated_interval_ft
        self.afe_gross_dollar = afe_gross_dollar
        self.well_cost: float = well_cost
        self.seller_effective_gross_nri_percentage = seller_effective_gross_nri_percentage
        self.seller_net_nri_percentage = seller_net_nri_percentage
        self.seller_gross_for_sale_percentage = seller_gross_for_sale_percentage
        self.afe_gwi_for_sale_net_capital_dollar = afe_gwi_for_sale_net_capital_dollar
        self.enverus_rkb_elevation_ft = enverus_rkb_elevation_ft
        self.bhl_tvd_ss_ft = bhl_tvd_ss_ft
        self.afe_in_landing_zone_hyp_spacing_ft = afe_in_landing_zone_hyp_spacing_ft
        self.state = state
        self.county = county
        self.tx_abstract_southwest_corner = tx_abstract_southwest_corner
        self.tx_block_southwest_corner = tx_block_southwest_corner
        self.nw_township_southwest_corner = nw_township_southwest_corner
        self.nm_range_southwest_corner = nm_range_southwest_corner
        self.nm_tx_section_southwest_corner = nm_tx_section_southwest_corner
        self.nad_system = nad_system
        self.nad_zone = nad_zone
        self.x_surface_location = x_surface_location
        self.y_surface_location = y_surface_location
        self.x_first_take_point = x_first_take_point
        self.y_first_take_point = y_first_take_point
        self.x_last_take_point = x_last_take_point
        self.y_last_take_point = y_last_take_point
        self.x_bottom_hole = x_bottom_hole
        self.y_bottom_hole = y_bottom_hole
        self.latitude_surface_location = latitude_surface_location
        self.longitude_surface_location = longitude_surface_location
        self.latitude_first_take_point = latitude_first_take_point
        self.longitude_first_take_point = longitude_first_take_point
        self.latitude_last_take_point = latitude_last_take_point
        self.longitude_last_take_point = longitude_last_take_point
        self.latitude_bottom_hole = latitude_bottom_hole
        self.longitude_bottom_hole = longitude_bottom_hole
        self.legal_tx_abstract_surface_location = legal_tx_abstract_surface_location
        self.Legal_tx_block_surface_location = Legal_tx_block_surface_location
        self.legal_nw_township_surface_location = legal_nw_township_surface_location    
        self.legal_nm_tx_section_surface_location = legal_nm_tx_section_surface_location
        self.legal_fnl_surface_location = legal_fnl_surface_location
        self.legal_fsl_surface_location = legal_fsl_surface_location
        self.legal_fwl_surface_location = legal_fwl_surface_location
        self.legal_fel_surface_location = legal_fel_surface_location
        self.legal_tx_abstract_first_take_point = legal_tx_abstract_first_take_point
        self.Legal_tx_block_first_take_point = Legal_tx_block_first_take_point
        self.legal_nw_township_first_take_point = legal_nw_township_first_take_point
        self.legal_nm_tx_section_first_take_point = legal_nm_tx_section_first_take_point
        self.legal_fnl_first_take_point = legal_fnl_first_take_point
        self.legal_fsl_first_take_point = legal_fsl_first_take_point
        self.legal_fwl_first_take_point = legal_fwl_first_take_point    
        self.legal_fel_first_take_point = legal_fel_first_take_point
        self.legal_tx_abstract_last_take_point = legal_tx_abstract_last_take_point
        self.Legal_tx_block_last_take_point = Legal_tx_block_last_take_point
        self.legal_nw_township_last_take_point = legal_nw_township_last_take_point
        self.legal_nm_tx_section_last_take_point = legal_nm_tx_section_last_take_point
        self.legal_fnl_last_take_point = legal_fnl_last_take_point
        self.legal_fsl_last_take_point = legal_fsl_last_take_point
        self.legal_fwl_last_take_point = legal_fwl_last_take_point
        self.legal_fel_last_take_point = legal_fel_last_take_point
        self.legal_tx_abstract_bottom_hole = legal_tx_abstract_bottom_hole
        self.Legal_tx_block_bottom_hole = Legal_tx_block_bottom_hole
        self.legal_nw_township_bottom_hole = legal_nw_township_bottom_hole
        self.legal_nm_tx_section_bottom_hole = legal_nm_tx_section_bottom_hole
        self.legal_fnl_bottom_hole = legal_fnl_bottom_hole
        self.legal_fsl_bottom_hole = legal_fsl_bottom_hole
        self.legal_fwl_bottom_hole = legal_fwl_bottom_hole
        self.legal_fel_bottom_hole = legal_fel_bottom_hole
        self.perf_interval_ft = perf_interval_ft