name: Deploy AFE Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      command:
        description: 'Select the command to run'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set environment variables based on input
        id: set_env_vars
        run: |
          echo "TF_VAR_branch=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_ghpat=${{ secrets.AFE_PUBLIC_GH_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_appsecret=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "AWS_ACCESS_KEY_ID=${{ vars.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "TF_VAR_env=afe-prod" >> $GITHUB_ENV
            echo "TF_VAR_s3_bucket=afe-plss" >> $GITHUB_ENV
          else
            echo "AWS_ACCESS_KEY_ID=${{ vars.DEV_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "TF_VAR_env=afe-dev" >> $GITHUB_ENV
            echo "TF_VAR_s3_bucket=afe-plss-dev" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform commands
        run: |
          cd terraform

          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            terraform init -backend-config=backend-prod.tfvars
          else
            terraform init -backend-config=backend-dev.tfvars
          fi
          
          if [ "${{ github.event.inputs.command }}" == "plan" ]; then
            terraform plan 
          fi
          if [ "${{ github.event.inputs.command }}" == "apply" ]; then
            terraform apply -auto-approve
          fi
          if [ "${{ github.event.inputs.command }}" == "destroy" ]; then
            terraform destroy -auto-approve
          fi